// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SampleCodeFirst.Models;

namespace SampleCodeFirst.Migrations
{
    [DbContext(typeof(ToDoContext))]
    [Migration("20220411054704_seeddata")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SampleCodeFirst.Models.ToDoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToDoItem");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "In meeting need to discuss some point",
                            IsComplete = true,
                            name = "Meeting with management"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "List of items to buy",
                            IsComplete = false,
                            name = "Go For Shopping"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Here is task to do on a call",
                            IsComplete = true,
                            name = "Call someone to do task"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
